add updates modal (#34)
profcomff/webapp-ui pull request #95
Opened 2023-05-16 16:00 UTC by Sarkor2007

## Изменения
Опишите здесь на языке, понятном каждому, изменения, сделанные в исходном коде по пунктам.

## Реализации
Опишите здесь на языке, понятном каждому, что нового было добавлено в исходный код.

## Детали
Здесь можно описать технические детали по пунктам.

## Check-List
- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить black и isort?

***P.S. Проставьте x в квадратные скобки в нужных пунктах. Example: [x]***

2023-05-16 16:22 UTC, physphile requested changes

2023-05-16 16:22 UTC, physphile commented on package.json
> +    "sass": "^1.62.1",
`sass` мы не используем. Nesting уже реализован в ванильном `css`, так что вкупе с `PostCSS` получается очень хорошо

2023-05-16 16:22 UTC, physphile commented on src/components/TheUpdates.vue
> +<script setup lang="ts">
Вот этот компонент хотелось бы разделить. Сделать базовый компонент `IrdomDialog`, который будет просто отрисовывать окошко в котором будет находиться `<slot></slot>` и уже реализация этого базового компонента в компоненте `TheUpdates`

2023-05-16 16:22 UTC, physphile commented on src/components/TheUpdates.vue
> +					<img draggable="false" src="../assets/close.svg" alt="exit btn" />
По договоренности пишем `@/assets/close.svg`

2023-05-16 16:22 UTC, physphile commented on src/components/TheUpdates.vue
> +<style scoped lang="scss">
Ключевой атрибут `scoped`, говорит нам о том, что стили описанные здесь никак не будут влиять на какие-либо другие компоненты, так что БЭМ подход здесь можно не использовать

2023-05-16 16:22 UTC, physphile commented on src/views/apps/AppsView.vue
> +import TheUpdates from '@/components/TheUpdates.vue';
Компоненты, которые находятся в `@/components` необходимо сначала реэкспортировать в файле `@/components/index.ts`, а затем импортировать как ```import {TheUpdates} from '@/components'```

2023-05-16 16:22 UTC, physphile commented on src/views/apps/AppsView.vue
> +	modalIsOpen.value = !modalIsOpen.value;
полагаю, что CLOSE подразумевает только `modalIsOpen.value = false`

2023-05-16 16:22 UTC, physphile commented on src/views/apps/AppsView.vue
> +	setTimeout(closeModal, 500);
у меня вроде не работает этот таймаут

2023-05-22 09:16 UTC, physphile requested changes

2023-05-22 09:16 UTC, physphile commented on src/components/TheUpdates.vue
> +		<irdom-dialog @close="closeModal" :open="open">
А толку ты вынес `IrdomDialog`, если ты прям там все и прописал? Идея в том, что `IrdomDialog` реализует только показ и закрытие диалогового окна и там есть только один `<slot>`.  Затем, на основе этого базового компонента можно создать `<SlideDialog>`, который будет использовать `swiper.js` и в который можно будет пропсами прокинуть данные слайдов.

2023-05-22 09:16 UTC, physphile commented on src/views/apps/AppsView.vue
> +const isOpenModal = () => {
Тогда лучше `toggleModal` назвать, это функция все-таки

2023-07-05 18:21 UTC, grigoriev-semyon commented
@Sarkor2007 когда ждать пр?

2023-08-10 20:44 UTC, dyakovri commented
Мы перешли на вьютифай

2023-08-10 20:44 UTC, closed without merging